---
title: "Designing and Programming Survey Forms"
author: "Ayush Patel"
format: html
---

# Welcome

This is the landing page for the modules on designing and programming survey forms. This module is a part of the Data, Democracy & Development (DDD) summer field practice course.

# About you

-   New to designing survey questionnaires.
-   Has an undergrad degree or is enrolled in one or is enrolled in a post grad program.
-   Knows foundations of stats and econ/policy principles.

# Pre-requisits and other necessary setup

-   Create a free account on the SurveyCTO Website
-   Download the SurveyCTO collect app on your phone

# Learning Outcomes for this module

-   Will be able to design, program and implement survey questionnaires
-   Will learn data viz for descriptive and exploratory analysis

# Resources

-   [Link to Lecture Slides](slides/03-05-2025-mod-designing-and-programming-survey-forms.html)
-   [Dimewiki SurveyCTO Programming](https://dimewiki.worldbank.org/SurveyCTO_Programming)
-   [Dimewiki SurveyCTO Server Mangement](https://dimewiki.worldbank.org/SurveyCTO_Server_Management)
-   [Dimewiki Best Practices](https://dimewiki.worldbank.org/SurveyCTO_Best_Practices)
